name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyright
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        cd ${{ github.workspace }}
        echo "Running flake8 on Python files..."
        find . -type f -name "*.py" -exec python3 -m flake8 {} +
        echo "flake8 analysis completed successfully."
#    - name: Type checking with Pyright
#      run: |
#        cd ${{ github.workspace }}
#        echo "Running Pyright for type checking..."
#        find . -type f -name "*.py" -exec python3 -m pyright {} +
#        echo "Pyright type checking completed successfully."
